### ISSUE TITLE
fluentpos-lite.cart

### ISSUE THREAD

**Issue by AbuHelweh** [fullstackhero/dotnet-microservices-boilerplate#59]
docker compose -f "./deployments/docker-compose/infrastructure.yml" -f "./deployments/docker-compose/docker-compose.yml" up

time="2023-04-26T15:34:58+04:00" level=warning msg="The \"USER_PROFILE\" variable is not set. Defaulting to a blank string."
[+] Running 1/1
 ✘ cart Error                                                                                                                                                                           3.5s 
Error response from daemon: pull access denied for fluentpos-lite.cart, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by iammukeshm** [comment]
I have not pushed this cart image to my docker hub yet. However, please wait for a couple of weeks. I am completely changing the structure of this repository for a cleaner version. The work is ongoing at the revamp branch.

https://github.com/fullstackhero/dotnet-microservices-boilerplate/tree/revamp
