### ISSUE TITLE
Failed to Import Thunder Client

### ISSUE THREAD

**Issue by AbuHelweh** [fullstackhero/dotnet-microservices-boilerplate#60]
Hi, 

I want to load the import the thunder client Environment and collection in vscode but Im getting error 
Failed to Import: 1 files - thunderEnvironment.json
Failed to Import: 1 files - thunderCollection.json

Please advice

**Comment by iammukeshm** [comment]
You can simply open up the repository in Visual Code, and open up the ThunderClient extension. You don't really have to explicitly load anything. It will automatically load all the required configurations.
