### ISSUE TITLE
fluentpos-lite

### ISSUE THREAD

**Issue by AbuHelweh** [fullstackhero/dotnet-microservices-boilerplate#61]
Why do you have fluentpos-lite folder inside projects folder? 

can we rename it ?

**Comment by iammukeshm** [comment]
it's a sample project that will use the template's framework. This will be a starting point later on. 
What do you want to rename this to?

**Comment by AbuHelweh** [comment]
The problem is not with the folder name only, its also used as namespace inside the projects
the revamp version has no API gateway project

**Comment by iammukeshm** [comment]
all changes are now merged to the main branch. gateway is also added.
