### ISSUE TITLE
access swagger catalog service through gateway

### ISSUE THREAD

**Issue by AbuHelweh** [fullstackhero/dotnet-microservices-boilerplate#66]
direct call without YARP its working

access swagger catalog service through gateway https://localhost:7002/api/catalog/swagger/index.html
![image](https://user-images.githubusercontent.com/5153946/236693113-87ecaf28-1768-4abe-b4fd-6710bf93b470.png)

**Comment by iammukeshm** [comment]
The Swagger is available at the /docs endpoint now.

Gateway -> https://localhost:7002/api/catalog/docs/index.html
Catalog -> https://localhost:7003/docs/index.html
