### ISSUE TITLE
token validation in microservices

### ISSUE THREAD

**Issue by devdgupta** [fullstackhero/dotnet-microservices-boilerplate#70]
I wanted to add the token validation on the Gateway and each services  instead of Identity server but unable to do that.
Any Suggestion is highly appreciated.

**Comment by iammukeshm** [comment]
so, that's already possible for OpenId auth. You can refer to the `AddOpenIdAuth` extension which is responsible for validating JWTs against an Issuer URL. The configurations are part of the `OpenIdOptions` in the appsettings.json file.
